name: "Lint, Typecheck and Formatting"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Installing dependencies from lockfile
        run: pnpm install --frozen-lockfile
      - name: Running quality checks
        run: pnpm check-quality

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Installing dependencies from lockfile
        run: pnpm install --frozen-lockfile
      - name: Running Build
        run: pnpm build
